INFLUXDB_GOLANG_TEST_VERSION = 1.1
INFLUXDB_GOLANG_TEST_SITE = $(INFLUXDB_GOLANG_TEST_PKGDIR)/src
INFLUXDB_GOLANG_TEST_SITE_METHOD = local
INFLUXDB_GOLANG_TEST_LICENSE = BSD-3-Clause
INFLUXDB_GOLANG_TEST_LICENSE_FILES = LICENSE

 $(eval $(golang-package))
